services:
  opus_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: opus_dev_image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:20210121daihyou@db:5432/opus_dev
      - JWT_SECRET=20210121daihyou
    volumes:
      - .:/app
    command: docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20210121daihyou
      POSTGRES_DB: opus_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: