version: '3.8'

services:
  opus_dev:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: opus_dev:amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  node_modules: